- name: Tower test sample
  hosts: all
  tasks:
    - name: Init Message
      debug:
        msg: "Tower test start!"

    - name: Get id
      shell: hostname
      register: runhostname

    - name: Print hostname
      debug:
        msg: "{{ runhostname }}"
      ignore_errors: yes

    - name: Print hostname from facts
      debug:
        msg: "Facts hostname {{ ansible_hostname }}"
