- name: Tower test sample
  hosts: all
  tasks:
    - name: Init Message
      debug:
        msg: "Tower test start!"

    - name: Get id
      shell: hostname
      register: runhostname.stdout

    - name: Print hostname
      debug:
        msg: "{{ runhostname }}"
      ignore_errors: yes

    - name: Print facts
      debug:
        msg: "Facts: {{ ansible_hostname }} -  {{ ansible_default_ipv4.address }} - {{ ansible_fqdn }}"
