- name: Tower test sample
  hosts: all
  tasks:
    - name: Init Message
      debug:
        msg: "Tower test start!"

    - name: Get id
      shell: hostname
      register: runhost
      changed_when: "runhost.rc > 0"

    - name: Print hostname
      debug:
        msg: "{{ runhost.stdout }}"

    - name: Print facts
      debug:
        msg: |
          Facts:
          {{ ansible_hostname }} -  {{ ansible_default_ipv4.address }} - {{ ansible_fqdn }}
          {{ ansible_os_family }} {{ ansible_distribution_major_version }} {{ ansible_distribution_minor_version }}
